[webservers]
web-1 ansible_host=158.160.45.23 fqdn=web-1.ru-central1.internal
web-2 ansible_host=158.160.57.217 fqdn=web-2.ru-central1.internal

[databases]
main ansible_host=51.250.66.233 fqdn=main.ru-central1.internal
replica ansible_host=89.169.155.166 fqdn=replica.ru-central1.internal

[storage]
storage ansible_host=93.77.179.14 fqdn=storage.ru-central1.internal
